### ISSUE TITLE
AWS::Lightsail::Instance Cannot create Windows instance

### ISSUE THREAD

**Issue by jfan9** [aws-cloudformation/aws-cloudformation-resource-providers-lightsail#62]
Hi Team,

This is a bug that we cannot create windows instance with `AWS::Lightsail::Instance`, even with `AddOn` or No `AddOn` defined in the template.

Error message:
```
Resource handler returned message: "The AddOn is AutoSnapshot not supported for the given resource LightsailInstanceUS2a
```

According the code [ln154](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-lightsail/blob/main/aws-lightsail-instance/src/main/java/software/amazon/lightsail/instance/helpers/resource/AddOns.java#L154), it shows  `// If AddOn Not present -> Disable`, but with Windows instance creation, no matter `AddOn` is present or not, the Error will occur.

**Comment by godduv-amzn** [comment]
This issue has been fixed.
